config/routes.rb
Rails.application.routes.draw do

   devise_for :users
   root 'products#index'
   resources :orders, only: [:index]
   resources :deliveries , only: [:index]
   resources :parent_categories, only: [:index]
   resources :book_genres, only: [:index, :show]
   resources :reviews, only: [:new]
   resources :users, only: [:edit, :update] do
    resources :likes, only: [:index]
  end
   resources :products, only: [:index, :show, :update] do
     resources :orders, only: [:show]
     resources :likes, only: [:create, :destroy]

      post '/add_product' => 'orders#add_product'
      patch '/update_product' => 'orders#update_product'
      delete '/delete_product' => 'orders#delete_product'
    collection do
      get 'search'
    end
   end
    resources :tokens, only: [:new ,:index] do
      collection do
        post 'token'
        get 'pay'
      end
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookimage.rb
class Bookimage < ApplicationRecord
  belongs_to :product
  #mount_uploader :image_url, ImageUploader

end

app/models/books_image.rb
class BooksImage < ApplicationRecord
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
    has_many :products
    belongs_to :user


  end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
end
 

app/models/product.rb
class Product < ApplicationRecord
  has_many :bookimages
  has_one :registrationinformation
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/registrationinformation.rb
class Registrationinformation < ApplicationRecord
  belongs_to :product
end

app/models/scraping.rb
class Scraping

  def self.product_urls
    agent = Mechanize.new
    links = []

    #while true
        current_page = agent.get("https://www.e-hon.ne.jp/bec/SE/List?dcode=05&ccode=06&scode=02&listcnt=30&Genre_id=050602")
        elements = current_page.search('.listColumn .title a')
        elements.each do |ele|
            links << ele.get_attribute('href')
        end
    #end
    links.each do |link|
        get_info(link)
    end
  end

  # def self.get_product(link)
  #    agent = Mechanize.new
  #    page = agent.get(link)
  #    name = page.at('#main .rightCol .itemTitle').inner_text if page.at('#main .rightCol .itemTitle')
  #    description = page.search('.commentDetail p').inner_text if page.search('.commentDetail p')
  #    price = page.search('.mainItemTable tbody tr')[3].inner_text.gsub(/[^\d]/, "").to_i

  #    product = Product.new(name: name, description: description, price: price)
  #    product.save
  #  end

  # def self.image_urls(link)
  #   agent = Mechanize.new
  #   page = agent.get(link)
  #   image_url = page.at('.mainItemImg img')[:src]

  #   booksimage = Bookimage.new(image_url: image_url)
  #   booksimage.save
  # end

  def self.get_info(link)
      agent = Mechanize.new
      page = agent.get(link)
      isbn = page.search('.codeSelect')[0].inner_text
      pubiilsher = page.search('.mainItemTable tbody tr td')[0].inner_text
      saledate = page.search('.mainItemTable tbody tr td')[1].inner_text

      info = Registrationinformation.new(isbn: isbn, pubiilsher: pubiilsher, saledate: saledate)
      info.save
  end

end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tokens
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_variables, except: [:index]

  def index
    @like = Like.where(user_id: params[:user_id])

  end
  def create
    @like = Like.new(
      product_id: params[:product_id],
      user_id: current_user.id)
    @like.save
    end

  def destroy
    like = Like.find_by(
      product_id: params[:product_id],
      user_id: current_user.id)
    like.destroy
    end

  private

    def like_params
      params.require(:like).permit(:product_id, :user_id)

    end

    def set_variables
    @product = Product.find(params[:product_id])
    @likes = Like.where(product_id: params[:product_id])
    @id_name = "#like-link-#{@product.id}"
    @id_heart = "#heart-#{@product.id}"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :setup_order_product, only: [:add_product, :update_product, :delete_product]

    def index
      if current_user.orders.last != nil
      @current = current_user.orders.last
      @order_products = @current.order_products
      @quantity = []
      @order = []

      num = 0
        @order_products.each do |order|
          @order << order
          @quantity << order.product.price * order.quantity
          @total_count = num += order.quantity
        end


      sub = 0
        @quantity.each do |quantity|
          @total_price = sub += quantity
        end

      end
    end

  def show
    @order_product = current_order.order_products
  end

  def add_product
    if @order_product.blank?
      @order_product = current_order.order_products.build(params_order)
    else
      @order_product.quantity += params[:order][:order_products][:quantity].to_i
    end
    @order_product.save
    render :show
  end

  def update_product
    @order_product.update(quantity: params[:product][:order_products][:quantity].to_i)
    render json: { status: 'success'}

  end

  def delete_product

    @order_product.destroy
    render json: { status: 'success'}
  end

  private

  def params_order
   params.require(:order).permit(order_products: [:quantity])[:order_products].merge(product_id: params[:product_id])
  end

  def setup_order_product
    current_order

    @order_product = current_order.order_products.find_by(product_id: params[:product_id])

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController

  def new
  end

  def token
    Payjp.api_key = 'pk_test_1bd65f74de4d0be46949ad88'
    token = Payjp::Token.create(
      :card => {
        :number => params[:number],
        :cvc => params[:cvc],
        :exp_month => params[:exp_month],
        :exp_year => params[:exp_year]
       }
     )
    Token.create(token: token.id, user_id: current_user.id)


  end

  def index
  end


  def pay
      @tokens = Token.where(user_id: current_user.id)
      @token = @tokens.last.token
      @current = current_user.orders.last
      @order_products = @current.order_products
      @quantity = []
      @order_products.each do |order|
        @quantity << order.product.price * order.quantity
      end

      sub = 0
      @quantity.each do |quantity|
        @total_price = sub += quantity
      end

    Payjp.api_key = 'sk_test_f6fb174ceb7bc83bab497a79'
    charge = Payjp::Charge.create(
        :amount => @total_price,
        :card => @token,
        :currency => 'jpy',
      )
      @order_products.delete_all

      flash[:notice] = "支払い完了"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_genres_helper.rb
module BookGenresHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/likes/_like.html.haml
.like-boxs{id: "like-link-#{product.id}"}
  - if user_signed_in?
    - if product.like_user(current_user.id)
      = button_to product_like_path(id: product.id, product_id: product.id), method: :delete, id: "like-button", remote: true do
        .icon{id: "heart-#{product.id}"}
          = image_tag("icon_red_heart.svg")
          %span
            = "LIKE"
            = product.likes.count
    - else
      = button_to product_likes_path(product),method: :post,id: "like-button", remote: true do
        .icon{id: "heart-#{product.id}"}
          = image_tag("icon_heart.svg")
          %span
            = "LIKE"
            = product.likes.count
  - else
    = button_to new_user_session_path, id: "like-button" do
      .icon
        = image_tag("github.svg")
        %span
          = "SIGN IN"

app/views/likes/_like_index.html.haml
.sc-list-body.sc-java-remote-feature{"data-name" => "Active Items"}
  %hr
    .a-carousel-viewport{:style => "margin-top: 15px;"}
      %ol.a-carousel
      - @like.each do |like|
        %li.a-carousel-card.acswidget-carousel__card{"aria-setsize" => "20", :style => "max-width:230px;"}
          - like.product.bookimages.each do |image|
            = link_to image_tag(image.image_url, style: " height: 140px; width: 110px;"),"/products/#{like.product.id}",:target => "_blank"
          .a-box-group.a-spacing-top-micro.acs_product-title
            = link_to "#{like.product.name}","/products/#{like.product.id}",:target => "_blank"
            .a-row.a-color-secondary
            = like.product.registrationinformation.determinetype
            .a-box-group.a-size-small.a-spacing-none.acs_product-price
              %span.a-size-base.a-color-price ¥
              %span.a-size-base.a-color-price
                = like.product.price
              %i.a-icon.a-icon-jp.a-icon-prime-jp{"aria-label" => "Prime JP"}
                %span.a-icon-alt Prime JP
  %hr

app/views/likes/create.js.erb
$('<%= @id_name %>').html('<%= j(render("likes/like", product: @product, likes: @likes, like: @like )) %>');

app/views/likes/destroy.js.erb
$('<%= @id_name %>').html('<%= j(render("likes/like", product: @product, likes: @likes )) %>');

app/views/orders/_order.html.haml
.sc-list-body.sc-java-remote-feature{"data-name" => "Active Items"}
  .a-row.sc-list-item.sc-list-item-border.sc-java-remote-feature
  - @order.zip(@quantity) do |order, quantity|
    .sc-list-item-content{id: "order_#{order.id}"}
      .a-row.a-spacing-base.a-spacing-top-base
        - order.product.bookimages.each do |image|
          .a-column.a-span8
            .a-fixed-left-grid
              .a-fixed-left-grid-inner{:style => "padding-left:115px"}
                .a-fixed-left-grid-col.a-float-lefts.a-col-left{:style => "width:115px;margin-left:-115px;float:left;"}
                  %a.a-link-normal.sc-product-link{:href => "/gp/product/4796687122/ref=ox_sc_act_image_1?smid=AN1VRQENFRJN5&psc=1"}
                    %img.sc-product-image{:alt => "#{order.product.name}", :height => "100", :src => "#{image.image_url}", :width => "100"}/
                .a-fixed-left-grid-col.a-col-right{:style => "padding-left:0%;float:left;"}
                  %ul.a-unordered-list.a-nostyle.a-vertical.a-spacing-mini
                    %li
                      %span.a-list-item
                        %a.a-link-normal.sc-product-link{:href => "/products/#{order.product.id}"}
                          %span.a-size-medium.sc-product-title.a-text-bold
                            = order.product.name
                        %span.a-size-base.sc-product-creator
                          = order.product.name
                    %li
                      %span.a-list-item
                        %span.a-size-small.a-color-secondary.sc-product-binding
                          = order.product.registrationinformation.determinetype
                    %li
                      %span.a-list-item
                        %span.a-size-base.sc-product-creator ¥
                        %span.a-size-base.sc-product-creator{id: "price"}
                          = order.product.price
                    %li
                      %span.a-list-item
                        %span.a-size-small.a-color-secondary.sc-product-binding 注文個数　
                        %span.a-size-small.a-color-secondary.sc-product-binding{id: "count"}
                          = order.quantity
                  .a-row.sc-action-links
                    %span.a-size-small.sc-action-delete
                      %span.a-declarative
                      = button_to "削除" , product_delete_product_path(order.product.id), method: :delete, style: "border-color: #cba957 #bf942a #aa8326; background: #f0c14b; border-radius: 10px; width: 60px; background: #f4d078; background: -webkit-linear-gradient(top,#f7dfa5,#f0c14b); background: linear-gradient(to bottom,#f7dfa5,#f0c14b);",remote: true
          .a-column.a-span2.a-text-left
            %p.a-spacing-small
              %span.a-size-medium.a-color-price.sc-price.sc-white-space-nowrap.sc-product-price.sc-price-sign.a-text-bold ¥
              %span.a-size-medium.a-color-price.sc-price.sc-white-space-nowrap.sc-product-price.sc-price-sign.a-text-bold{id: "prices"}
                = quantity
          .a-column.a-span2.a-text-right.sc-action-links.a-span-last
            .a-row.a-spacing-base.sc-action-quantity.sc-action-quantity-right{"data-old-value" => "1"}
              .sc-invisible-when-no-js
                = form_for(order.product, url: product_update_product_path(order.product.id),remote: true) do |f|
                  = f.fields_for :order_products do |o|
                    = o.label :quantity, "数量"
                    = o.select :quantity, [[1,1],[2,2],[3,3],[4,4],[5,5]]
                    = o.submit "変更"
      %hr

app/views/orders/show.html.haml
#a-page
  .huc-v2-page-container
    .a-row
      .a-box.a-onlychild.a-color-alternate-background.huc-v2-order-row.huc-v23-order-row
        .a-box-inner
          .a-row.huc-v2-table-row.full-width
            #huc-v2-order-row-items.a-row.huc-v2-table-col.width-fit-content
              #huc-v2-order-row-icon.huc-v2-table-col.a-alert.a-alert-success
                %i.a-icon.a-icon-alert
              .huc-v2-table-col
                .a-box.a-box-thumbnail.huc-middle-vertical.huc-no-radius.huc-v2-order-row-image-box.huc-green-border
                  .a-box-inner
                    %img.huc-no-radius.huc-v2-order-row-image.huc-v2-table-col{alt: "", src: "https://images-na.ssl-images-amazon.com/images/I/51CGypjLrvL._SX348_BO1,204,203,200_.jpg"}
                    .huc-v2-table-col
                      %i.a-icon.a-icon-popover.huc-v2-order-row-down-arrow
            #huc-v2-order-row-messages.a-row.huc-v2-table-col.width-fit-content
              .huc-v2-color-success
                %h1.a-size-medium.a-text-bold 追加されました
            #huc-v2-order-row-center.a-row.huc-v2-table-col
              #huc-v2-order-row-center-inner.a-row.full-width
                .a-row.huc-v2-table-row.full-width.order-row-base-height
                  .a-row.huc-v2-table-col
                    #hlb-subcart.a-row.huc-v2-subcart.a-size-small
                      .a-row.a-spacing-micro
                        %span.a-size-medium.a-align-center.huc-subtotal
                          %span
                            %b> カートの小計
                            （商品1点）:
                          %span.a-color-price.hlb-price.a-inline-block.a-text-bold ￥ 2,592
                      /
                        \##ポイント獲得を表示する記述##  <div class="a-row"> <span>この注文での獲得ポイント:</span> <span class="hlb-price">0pt</span> <span id="hlb-ship-message" class="a-size-small a-inline-block">
                        <span>
                        <b>通常配送無料</b> <a href="http://www.amazon.co.jp/gp/help/customer/display.html?nodeId=642982" target="SuperSaverShipping" onclick="return amz_js_PopWin('http://www.amazon.co.jp/gp/help/customer/display.html?nodeId=642982','SuperSaverShipping','width=550,height=550,resizable=1,scrollbars=1,toolbar=0,status=0');">詳細</a></span>
                        </span>
                        </div> ##ポイント獲得を表示する記述##
            #huc-v2-order-row-buttons.a-row.huc-v2-table-col
              #huc-v2-subcart-buttons-wrapper.a-row.a-text-right
                .huc-width-fit-content
                  .a-row
                    %span.a-declarative{"data-action" => "huc-view-cart", "data-huc-view-cart" => "{\"formID\":\"hlb-message-form\"}"}
                      %span#hlb-view-cart.a-button.huc-v2-view-cart.huc-spacing-right-mini.huc-button-large
                        %span.a-button-inner
                          #hlb-view-cart-announce.a-button-text
                            = link_to "カートの編集", orders_path
                    %span#hlb-ptc-btn.a-button.a-button-primary.hlb-checkout-button.huc-v2-primary-button.huc-button-large
                      %span.a-button-inner
                        #hlb-ptc-btn-native.a-button-text.a-text-center
                          = link_to "レジに進む", tokens_path
    #huc-v2-message-group.a-box-group.huc-v2-message-box-group
      #huc-v2-box-vas.a-box.a-spacing-base.a-spacing-top-micro.a-color-base-background.huc-v2-message-box.huc-v2-box-vas.huc-no-radius.a-hidden
        .a-box-inner.a-padding-base
          .huc-v2-arrow-up-border
          .huc-v2-arrow-up-inner
          #vas.a-row.a-hidden.hlb-vas
    #huc-v2-cobrand-stripe.a-row
      #huc-first-upsell-row.a-row.a-spacing-top-small{role: "complementary"}
        .a-row.a-spacing-small.a-size-large.huc-v2-upsell-title
          %h2.a-size-large
            %i{title: "本一覧"} 商品一覧
        .a-row.huc-position-rel
          .a-row.huc-v2-upsell-row
            .a-row.huc-v2-upsell-column.huc-position-rel.a-spacing-medium
              #upsell_0_0.huc-v2-upsell-box.huc-upsell-big-face-box
                .huc-upsell-big-face-box-inner
                  .a-link-normal.huc-v2-upsell-item-image.huc-to-dp-url
                  = link_to image_tag('https://images-fe.ssl-images-amazon.com/images/I/91Q1vEscp1L._SL150_.jpg',{alt: "", border: "0",})
            .a-row.huc-v2-upsell-column.huc-position-rel.a-spacing-medium
              #upsell_0_0.huc-v2-upsell-box.huc-upsell-big-face-box
                .huc-upsell-big-face-box-inner
                  .a-link-normal.huc-v2-upsell-item-image.huc-to-dp-url
                  = link_to image_tag('https://images-fe.ssl-images-amazon.com/images/I/51ic8vDPfvL._SL150_.jpg',{alt: "", border: "0",})
        #huc-v2-bottom-order-row-with-divider.a-row.a-text-center
          #huc-v2-bottom-order-row.a-box
            .a-box-inner
              / subtotal begins
              #hlb-bottom-subcart.a-row.huc-v2-row-col
                %span.a-size-medium.a-align-center.huc-subtotal
                  %span
                    %b> カートの小計
                    （商品1点）:
                  %span.a-color-price.hlb-price.a-inline-block.a-text-bold ￥ 2,592
              / subtotal ends
              / buttons begin
              .a-row.huc-v2-row-col
                .a-row.a-text-right
                  .huc-width-fit-content
                    .a-row
                      %span.a-declarative{"data-action" => "huc-view-cart", "data-huc-view-cart" => "{\"formID\":\"hlb-message-form\"}"}
                        %span#huc-v2-button-view-cart.a-button.huc-v2-view-cart.huc-spacing-right-mini.huc-button-large
                          %span.a-button-inner
                            #huc-v2-button-view-cart-announce.a-button-text
                              = link_to "カートの編集"
                      %span#hlb-ptc-btn-bottom.a-button.a-button-primary.hlb-checkout-button.huc-v2-primary-button.huc-button-large
                        %span.a-button-inner
                          #hlb-ptc-btn-native-bottom.a-button-text.a-text-center
                            = link_to "レジに進む"

app/views/tokens/index.html.haml
.order-confirm
  .order-confirm__top
    %p.order-confirm__top__subject 注文内容を確認する・変更する
    .order-confirm__top__description
      %p.order-confirm__top__description__top 下の『注文を確定する』ボタンを押してご注文いただくことで、お客様は当サイトのプライバシー規約および利用規約の同意の上、消費をご注文されたことになります。
      %p.order-confirm__top__description__center Amazonマーケットプレイスの商品をご注文された場合、お客様は当サイトのAmazonマーケットプレイス参加規約、出店型出品者の返品ポリシー及びプライバシーポリシー、その他の販売条件、および一部の出店型出品者から商品やサービスのご案内が届くことについても同意されたことになります。
      %p.order-confirm__top__description__bottom Amazonマーケットプレイスの商品を購入する場合は、所定の配送料がかかります。『注文を確定する』ボタンをクリックする前に、配送料と注文合計をご確認ください。
  .order-confirm__left
    .order-confirm__left__top
      .order-confirm__left__top__left
        %p.order-confirm__left__top__left__subject お届け先住所
        = link_to "変更", "", class: "order-confirm__left__top__left__change"
        %p.order-confirm__left__top__left__address
          ローソン道玄坂二丁目
          %br 150-0043
          %br 東京都渋谷区道玄坂2-20-26
      .order-confirm__left__top__center
        %p.order-confirm__left__top__center__subject 支払い方法
        = link_to "変更" ,"tokens/new", class: "order-confirm__left__top__center__change"
        %p.order-confirm__left__top__center__pay コンビニ・ATM・ネットバンキング・電子マネー払い
        %p.order-confirm__left__top__center__description ＊お支払い番号は出荷準備に入り次第発行されます。
      .order-confirm__left__top__right
        %p.order-confirm__left__top__right__description Amazonギフト券・Amazonショッピングカードまたはクーポン：
        %input{type: "text", placeholder: "コードを入力",class: "order-confirm__left__top__right__form"}
        %input{type: "submit", value: "適用",class: "order-confirm__left__top__right__submit"}
    .order-confirm__left__center
      %p.order-confirm__left__center__description 注文確認前に受取人名を必ずご確認ください。受取人名には身分証明書に記載されている名前を使用してください。
      %p.order-confirm__left__center__name 受取人:サルカワくん
      = link_to "変更","", class: "order-confirm__left__center__change"
    .order-confirm__left__bottom
      %p.order-confirm__left__bottom__date お届け予定日: 2017年4月10日-2017年4月18日
      .order-confirm__left__bottom__item
        .order-confirm__left__bottom__item__picture
        .order-confirm__left__bottom__item__data
          %p.order-confirm__left__bottom__item__data__name ゼルダの伝説
          %p.order-confirm__left__bottom__item__data__price ¥6473
          %p.order-confirm__left__bottom__item__data__count 数量: 1
          %p.order-confirm__left__bottom__item__data__company Amazon.japan
  .order-confirm__right
    .order-confirm__right__top
      .order-confirm__right__top__order
        = form_tag("pay",method:"get",datakey:"pk_test_ec9c64f2f699515034a1831b ") do
          %input{:type => "submit", class: "order-submit", value: "注文を確定する"}/
    .order-confirm__right__center
      %p.order-confirm__right__center__subject 注文内容
    .order-confirm__right__bottom
      %p.order-confirm__right__bottom__money ご請求金額:
      %p.order-confirm__right__bottom__price ¥6473

app/views/tokens/pay.html.haml
.purchase-completion
  .purchase-completion__thanks
    %p ありがとうございます。注文が確定されました。
  .purchase-completion__confirmation
    %p 確認のEメールを送信しました。
  .purchase-completion__number
    %p 注文番号: 11111111111
  .purchase-completion__data
    .purchase-completion__data__item
      %p ・ 1つの商品を次のお届け先へ発送します。
    .purchase-completion__data__consignor
      %p Amazon.com Int'l Sales, inc.
    .purchase-completion__data__date
      %p お届け予定日:
    .purchase-completion__data__number
      %p 2015年5月22日 -2015年5月24日
  .purchase-completion__link
    .purchase-completion__link__expression
      = link_to "注文を表示する"
    .purchase-completion__link__question
      = link_to "・購入についてのよくある質問"
    .purchase-completion__link__point
      = link_to "・Amazonポイントを確認する"
  .purchase-completion__share
    =link_to "シェアする"
    %i.fa.fa-envelope-o.fa-lg
    %i.fa.fa-facebook-official.fa-lg
    %i.fa.fa-twitter.fa-lg

app/views/tokens/token.html.haml
.order-confirm
  .order-confirm__top
    %p.order-confirm__top__subject 注文内容を確認する・変更する
    .order-confirm__top__description
      %p.order-confirm__top__description__top 下の『注文を確定する』ボタンを押してご注文いただくことで、お客様は当サイトのプライバシー規約および利用規約の同意の上、消費をご注文されたことになります。
      %p.order-confirm__top__description__center Amazonマーケットプレイスの商品をご注文された場合、お客様は当サイトのAmazonマーケットプレイス参加規約、出店型出品者の返品ポリシー及びプライバシーポリシー、その他の販売条件、および一部の出店型出品者から商品やサービスのご案内が届くことについても同意されたことになります。
      %p.order-confirm__top__description__bottom Amazonマーケットプレイスの商品を購入する場合は、所定の配送料がかかります。『注文を確定する』ボタンをクリックする前に、配送料と注文合計をご確認ください。
  .order-confirm__left
    .order-confirm__left__top
      .order-confirm__left__top__left
        %p.order-confirm__left__top__left__subject お届け先住所
        = link_to "変更", "", class: "order-confirm__left__top__left__change"
        %p.order-confirm__left__top__left__address
          ローソン道玄坂二丁目
          %br 150-0043
          %br 東京都渋谷区道玄坂2-20-26
      .order-confirm__left__top__center
        %p.order-confirm__left__top__center__subject 支払い方法
        = link_to "変更" ,"new", class: "order-confirm__left__top__center__change"
        %p.order-confirm__left__top__center__pay コンビニ・ATM・ネットバンキング・電子マネー払い
        %p.order-confirm__left__top__center__description ＊お支払い番号は出荷準備に入り次第発行されます。
      .order-confirm__left__top__right
        %p.order-confirm__left__top__right__description Amazonギフト券・Amazonショッピングカードまたはクーポン：
        %input{type: "text", placeholder: "コードを入力",class: "order-confirm__left__top__right__form"}
        %input{type: "submit", value: "適用",class: "order-confirm__left__top__right__submit"}
    .order-confirm__left__center
      %p.order-confirm__left__center__description 注文確認前に受取人名を必ずご確認ください。受取人名には身分証明書に記載されている名前を使用してください。
      %p.order-confirm__left__center__name 受取人:サルカワくん
      = link_to "変更","", class: "order-confirm__left__center__change"
    .order-confirm__left__bottom
      %p.order-confirm__left__bottom__date お届け予定日: 2017年4月10日-2017年4月18日
      .order-confirm__left__bottom__item
        .order-confirm__left__bottom__item__picture
        .order-confirm__left__bottom__item__data
          %p.order-confirm__left__bottom__item__data__name ゼルダの伝説
          %p.order-confirm__left__bottom__item__data__price ¥6473
          %p.order-confirm__left__bottom__item__data__count 数量: 1
          %p.order-confirm__left__bottom__item__data__company Amazon.japan
  .order-confirm__right
    .order-confirm__right__top
      .order-confirm__right__top__order
        = form_tag("pay",method:"get",datakey:"pk_test_1bd65f74de4d0be46949ad88") do
          %input{:type => "submit", class: "order-submit", value: "注文を確定する"}/
    .order-confirm__right__center
      %p.order-confirm__right__center__subject 注文内容
    .order-confirm__right__bottom
      %p.order-confirm__right__bottom__money ご請求金額:
      %p.order-confirm__right__bottom__price ¥6473