config/routes.rb
Rails.application.routes.draw do

   devise_for :users
   root 'products#index'
   resources :orders, only: [:index]
   resources :deliveries , only: [:index]
   resources :parent_categories, only: [:index]
   resources :book_genres, only: [:index, :show]
   resources :reviews, only: [:new]
   resources :users, only: [:edit, :update] do
    resources :likes, only: [:index]
  end
   resources :products, only: [:index, :show, :update] do
     resources :orders, only: [:show]
     resources :likes, only: [:create, :destroy]

      post '/add_product' => 'orders#add_product'
      patch '/update_product' => 'orders#update_product'
      delete '/delete_product' => 'orders#delete_product'
    collection do
      get 'search'
    end
   end
    resources :tokens, only: [:new ,:index] do
      collection do
        post 'token'
        get 'pay'
      end
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookimage.rb
class Bookimage < ApplicationRecord
  belongs_to :product
  #mount_uploader :image_url, ImageUploader

end

app/models/books_image.rb
class BooksImage < ApplicationRecord
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
    has_many :products
    belongs_to :user


  end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
end
 

app/models/product.rb
class Product < ApplicationRecord
  has_many :bookimages
  has_one :registrationinformation
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/scraping.rb
class Scraping

  def self.product_urls
    agent = Mechanize.new
    links = []

    #while true
        current_page = agent.get("https://www.e-hon.ne.jp/bec/SE/List?dcode=05&ccode=06&scode=02&listcnt=30&Genre_id=050602")
        elements = current_page.search('.listColumn .title a')
        elements.each do |ele|
            links << ele.get_attribute('href')
        end
    #end
    links.each do |link|
        get_info(link)
    end
  end

  # def self.get_product(link)
  #    agent = Mechanize.new
  #    page = agent.get(link)
  #    name = page.at('#main .rightCol .itemTitle').inner_text if page.at('#main .rightCol .itemTitle')
  #    description = page.search('.commentDetail p').inner_text if page.search('.commentDetail p')
  #    price = page.search('.mainItemTable tbody tr')[3].inner_text.gsub(/[^\d]/, "").to_i

  #    product = Product.new(name: name, description: description, price: price)
  #    product.save
  #  end

  # def self.image_urls(link)
  #   agent = Mechanize.new
  #   page = agent.get(link)
  #   image_url = page.at('.mainItemImg img')[:src]

  #   booksimage = Bookimage.new(image_url: image_url)
  #   booksimage.save
  # end

  def self.get_info(link)
      agent = Mechanize.new
      page = agent.get(link)
      isbn = page.search('.codeSelect')[0].inner_text
      pubiilsher = page.search('.mainItemTable tbody tr td')[0].inner_text
      saledate = page.search('.mainItemTable tbody tr td')[1].inner_text

      info = Registrationinformation.new(isbn: isbn, pubiilsher: pubiilsher, saledate: saledate)
      info.save
  end

end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tokens
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_variables, except: [:index]

  def index
    @like = Like.where(user_id: params[:user_id])

  end
  def create
    @like = Like.new(
      product_id: params[:product_id],
      user_id: current_user.id)
    @like.save
    end

  def destroy
    like = Like.find_by(
      product_id: params[:product_id],
      user_id: current_user.id)
    like.destroy
    end

  private

    def like_params
      params.require(:like).permit(:product_id, :user_id)

    end

    def set_variables
    @product = Product.find(params[:product_id])
    @likes = Like.where(product_id: params[:product_id])
    @id_name = "#like-link-#{@product.id}"
    @id_heart = "#heart-#{@product.id}"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :setup_order_product, only: [:add_product, :update_product, :delete_product]

    def index
      if current_user.orders.last != nil
      @current = current_user.orders.last
      @order_products = @current.order_products
      @quantity = []
      @order = []

      num = 0
        @order_products.each do |order|
          @order << order
          @quantity << order.product.price * order.quantity
          @total_count = num += order.quantity
        end


      sub = 0
        @quantity.each do |quantity|
          @total_price = sub += quantity
        end

      end
    end

  def show
    @order_product = current_order.order_products
  end

  def add_product
    if @order_product.blank?
      @order_product = current_order.order_products.build(params_order)
    else
      @order_product.quantity += params[:order][:order_products][:quantity].to_i
    end
    @order_product.save
    render :show
  end

  def update_product
    @order_product.update(quantity: params[:product][:order_products][:quantity].to_i)
    render json: { status: 'success'}

  end

  def delete_product

    @order_product.destroy
    render json: { status: 'success'}
  end

  private

  def params_order
   params.require(:order).permit(order_products: [:quantity])[:order_products].merge(product_id: params[:product_id])
  end

  def setup_order_product
    current_order

    @order_product = current_order.order_products.find_by(product_id: params[:product_id])

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index

  end

  def show
    @product = Product.find(params[:id])
    @image = @product.bookimages
    @registration = @product.registrationinformation
    @order = Order.new
    @user = current_user.id
    @like = Like.new
  end

  def update
  end

  def search
    @products = Product.where('name LIKE(?)', "%#{params[:keyword]}%").includes([:bookimages]).page(params[:page]).per(20)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController

  def new
  end

  def token
    Payjp.api_key = 'pk_test_1bd65f74de4d0be46949ad88'
    token = Payjp::Token.create(
      :card => {
        :number => params[:number],
        :cvc => params[:cvc],
        :exp_month => params[:exp_month],
        :exp_year => params[:exp_year]
       }
     )
    Token.create(token: token.id, user_id: current_user.id)


  end

  def index
  end


  def pay
      @tokens = Token.where(user_id: current_user.id)
      @token = @tokens.last.token
      @current = current_user.orders.last
      @order_products = @current.order_products
      @quantity = []
      @order_products.each do |order|
        @quantity << order.product.price * order.quantity
      end

      sub = 0
      @quantity.each do |quantity|
        @total_price = sub += quantity
      end

    Payjp.api_key = 'sk_test_f6fb174ceb7bc83bab497a79'
    charge = Payjp::Charge.create(
        :amount => @total_price,
        :card => @token,
        :currency => 'jpy',
      )
      @order_products.delete_all

      flash[:notice] = "支払い完了"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_genres_helper.rb
module BookGenresHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/products/_show-explanation.html.haml
.content
  %h3 商品の説明
  .content__introduce
    .content__introduce__subject
      %h4 内容紹介
      .content__introduce__subject__text
        = @product.description

app/views/products/_show-info.html.haml
.record-info
  %h3 登録情報
  %ul
    %li
      %b 単行本（ソフトカバー）:
      320ページ
    %li
      %b 出版社:
      = @registration.pubiilsher
    %li
      %b 言語:
      日本語
    %li
      %b ISBN-10:
      = @registration.isbn
    %li
      %b ISBN-13:
    %li
      %b 発売日：
      2008/2/7
    %li
      %b 梱包サイズ:
      21.2 x 15.2 x 1.8 cm
    %li
      %b おすすめ度：
      = link_to " 27件のカスタマーレビュー", "" , class: "review"
    %li
      %b Amazon 売れ筋ランキング:
      本 - 10,709位

app/views/products/_show-review.html.haml
.review
  .review__left
    .review__left__other
      .review__left__other__name
        %p 深夜ラジオいいね
      .review__left__other__subject
        %p リファレンスとしてよりも一味違うSQL文を目指す人におすすめ
      .review__left__other__data
        %p 2015年10月20日
      .review__left__other__type
        %p Amazonで購入
      .review__left__other__content
        %p 半分読み物ですね。しかし、そこがいいです。SQL文のポリシーや集合論、DBMSの高速化がわかって、納得して、スマートなSQL文を書けます。CASE式、Having句、自己結合、相関問い合わせが軽く使いこなせたらいいなあ。なにか、すっとする内容でした。
      .review__left__other__otherwise
        = link_to "役に立った", "/products/update",method: "patch" , class: "useful"
        = link_to "役に立たなかった" , "" , class: "useless"
        = link_to "コメント", "" ,class: "comment"
        = link_to "違反を報告", "", class: "violation"
  .review__right
    %h3 最近のカスタマレビュー
    .review__right__other
      .review__right__other__name
        %p ふじじ
      = render partial: "reviews/rate"
      .review__right__other__subject
        %p 素晴らしい
      .review__right__other__content
        %p SQL初心者でしたが、例題を踏まえながら書き方のテクニックをわかりやすく学ぶことができます。内容は少し古いですが、初心者にオススメの一冊です。
      .review__right__other__data
        %p 投稿日: 6ヶ月前

app/views/products/_show-top.html.haml
.top
  .top__left
    .top__left__picture
      .main
        - @image.each do |image|
          = image_tag(image.image_url)
      .sub
    .top__left__main
      .top__left__main__top
        = @product.name
        .date
          %p 2008/2/7
          %p 著者
      .top__left__main__middle
        .top
          = link_to "その他（2）の形式およびエディションを表示する"
        .left
          = link_to "kindle版 ¥ 2,400", "",class: "kindle"
          = link_to "今すぐお読みいただけます: 無料アプリ","",class: "apuri"
        .right
          = link_to "単行本(ソフトカバー¥ #{@product.price})","",class: "comic"
        .bottom
          = link_to "新しいお届け予定日を見るにはこちらをクリック"
      .top__left__main__bottom
        %img{:align => "left", :alt => "booksPMP", :border => "0", :height => "65", :src => "https://images-fe.ssl-images-amazon.com/images/G/09/2018/books/other/MATOME3-8_product_alart._CB497681712_.png", :width => "144"}/
        %p 書籍3冊以上を購入する際、クーポンコード「MATOME3」を入力すると最大8%ポイント還元！

  .top__right
    .top__right__top
      =link_to "シェアする"
      %i.fa.fa-envelope-o.fa-lg
      %i.fa.fa-facebook-official.fa-lg
      %i.fa.fa-twitter.fa-lg
    .like-box
      = render 'likes/like', product: @product, like: @like
    .top__right__main
      .price
        %p.a 新品
        .b
          %p ¥ #{@product.price}
        %p.c ポイント:
        %p.d 78pt(3%)
        = link_to "詳細はこちら", class: "e"
      %p.f 通常送料無料
      = link_to "詳細", class: "g"
      .rest
        %p.h 残り16点(入荷予定あり)
        %p.i 在庫状況について
        %p.j この商品は、Amazon.co.jpが販売、発送します。ギフトラッピングを利用できます。
      .cart
      = form_for(@order, url: product_add_product_path(@product.id)) do |f|
        = f.fields_for :order_products do |o|
          = o.label :quantity, "数量"
          = o.select :quantity, [[1,1],[2,2],[3,3],[4,4],[5,5]]
        .into-cart
          %label
            %br/
            %input{:name => "Checkbox", :type => "checkbox", :value => "チェックボックス"}/
            %p.k この注文でお急ぎ便、お届け日時指定便を無料体験  Amazonプライム無料体験について
          = f.submit "カートに入れる" ,class: "cart-in" do
            = fa_icon 'shopping-cart', class: "icon"
      .sign
        = link_to "1-Clickで注文する場合は、サインインをしてください。", "" ,class: "m"
      .adress
        = link_to "東京 102-0082‌ にお届け", "" , class: "n"
  .top__footer
    %h3 キャンペーンおよび追加情報
    .info
      %p ・ 【コンピュータ・IT】 プログラミング、アプリケーション関連書から各種試験対策まで コンピュータ・IT のページへ。
      %p ・  入会特典をこの商品に利用した場合、2,592円が592 円に ！ Amazonクラシックカード 新規ご入会で、2,000円分 の Amazonポイントプレゼント。 今すぐチェック

app/views/products/search.html.haml
/= render "shared/book_side_body"
.search-page
  .search-page__box
    - @products.each do |product|
      - product.bookimages.each do |image|
        .search-page__box__other
          %a.search-page__box__other__picture{href: "/products/#{product.id}"}
            / - @products.each do |product|
            /   - product.bookimages.each do |image|
            = image_tag(image.image_url, :size => "150x232")
          .search-page__box__other__data
            %a.search-page__box__other__data__name{href: "/products/#{product.id}"}
              / - @products.each do |product|
              = product.name
            .search-page__box__other__data__price
              / - @products.each do |product|
              %p ¥ #{product.price}
  = paginate(@products)

app/views/products/show.html.haml
= render "shared/book_search"
.wrapper
  = render partial: "products/show-top";
  = render partial: "products/show-explanation"
  = render partial: "products/show-info"
  = render partial: "products/show-review"

app/views/products/update.html.haml
.purchase-completion
  .purchase-completion__thanks
    %p ありがとうございます。注文が確定されました。
  .purchase-completion__confirmation
    %p 確認のEメールを送信しました。
  .purchase-completion__number
    %p 注文番号: 11111111111
  .purchase-completion__data
    .purchase-completion__data__item
      %p ・ 1つの商品を次のお届け先へ発送します。
    .purchase-completion__data__consignor
      %p Amazon.com Int'l Sales, inc.
    .purchase-completion__data__date
      %p お届け予定日:
    .purchase-completion__data__number
      %p 2015年5月22日 -2015年5月24日
  .purchase-completion__link
    .purchase-completion__link__expression
      = link_to "注文を表示する"
    .purchase-completion__link__question
      = link_to "・購入についてのよくある質問"
    .purchase-completion__link__point
      = link_to "・Amazonポイントを確認する"
  .purchase-completion__share
    =link_to "シェアする"
    %i.fa.fa-envelope-o.fa-lg
    %i.fa.fa-facebook-official.fa-lg
    %i.fa.fa-twitter.fa-lg