config/routes.rb
Rails.application.routes.draw do

   devise_for :users
   root 'products#index'
   resources :orders, only: [:index]
   resources :deliveries , only: [:index]
   resources :parent_categories, only: [:index]
   resources :book_genres, only: [:index, :show]
   resources :reviews, only: [:new]
   resources :users, only: [:edit, :update] do
    resources :likes, only: [:index]
  end
   resources :products, only: [:index, :show, :update] do
     resources :orders, only: [:show]
     resources :likes, only: [:create, :destroy]

      post '/add_product' => 'orders#add_product'
      patch '/update_product' => 'orders#update_product'
      delete '/delete_product' => 'orders#delete_product'
    collection do
      get 'search'
    end
   end
    resources :tokens, only: [:new ,:index] do
      collection do
        post 'token'
        get 'pay'
      end
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookimage.rb
class Bookimage < ApplicationRecord
  belongs_to :product
  #mount_uploader :image_url, ImageUploader

end

app/models/books_image.rb
class BooksImage < ApplicationRecord
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
    has_many :products
    belongs_to :user


  end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order
    belongs_to :product
end
 

app/models/product.rb
class Product < ApplicationRecord
  has_many :bookimages
  has_one :registrationinformation
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/scraping.rb
class Scraping

  def self.product_urls
    agent = Mechanize.new
    links = []

    #while true
        current_page = agent.get("https://www.e-hon.ne.jp/bec/SE/List?dcode=05&ccode=06&scode=02&listcnt=30&Genre_id=050602")
        elements = current_page.search('.listColumn .title a')
        elements.each do |ele|
            links << ele.get_attribute('href')
        end
    #end
    links.each do |link|
        get_info(link)
    end
  end

  # def self.get_product(link)
  #    agent = Mechanize.new
  #    page = agent.get(link)
  #    name = page.at('#main .rightCol .itemTitle').inner_text if page.at('#main .rightCol .itemTitle')
  #    description = page.search('.commentDetail p').inner_text if page.search('.commentDetail p')
  #    price = page.search('.mainItemTable tbody tr')[3].inner_text.gsub(/[^\d]/, "").to_i

  #    product = Product.new(name: name, description: description, price: price)
  #    product.save
  #  end

  # def self.image_urls(link)
  #   agent = Mechanize.new
  #   page = agent.get(link)
  #   image_url = page.at('.mainItemImg img')[:src]

  #   booksimage = Bookimage.new(image_url: image_url)
  #   booksimage.save
  # end

  def self.get_info(link)
      agent = Mechanize.new
      page = agent.get(link)
      isbn = page.search('.codeSelect')[0].inner_text
      pubiilsher = page.search('.mainItemTable tbody tr td')[0].inner_text
      saledate = page.search('.mainItemTable tbody tr td')[1].inner_text

      info = Registrationinformation.new(isbn: isbn, pubiilsher: pubiilsher, saledate: saledate)
      info.save
  end

end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tokens
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_variables, except: [:index]

  def index
    @like = Like.where(user_id: params[:user_id])

  end
  def create
    @like = Like.new(
      product_id: params[:product_id],
      user_id: current_user.id)
    @like.save
    end

  def destroy
    like = Like.find_by(
      product_id: params[:product_id],
      user_id: current_user.id)
    like.destroy
    end

  private

    def like_params
      params.require(:like).permit(:product_id, :user_id)

    end

    def set_variables
    @product = Product.find(params[:product_id])
    @likes = Like.where(product_id: params[:product_id])
    @id_name = "#like-link-#{@product.id}"
    @id_heart = "#heart-#{@product.id}"
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :setup_order_product, only: [:add_product, :update_product, :delete_product]

    def index
      if current_user.orders.last != nil
      @current = current_user.orders.last
      @order_products = @current.order_products
      @quantity = []
      @order = []

      num = 0
        @order_products.each do |order|
          @order << order
          @quantity << order.product.price * order.quantity
          @total_count = num += order.quantity
        end


      sub = 0
        @quantity.each do |quantity|
          @total_price = sub += quantity
        end

      end
    end

  def show
    @order_product = current_order.order_products
  end

  def add_product
    if @order_product.blank?
      @order_product = current_order.order_products.build(params_order)
    else
      @order_product.quantity += params[:order][:order_products][:quantity].to_i
    end
    @order_product.save
    render :show
  end

  def update_product
    @order_product.update(quantity: params[:product][:order_products][:quantity].to_i)
    render json: { status: 'success'}

  end

  def delete_product

    @order_product.destroy
    render json: { status: 'success'}
  end

  private

  def params_order
   params.require(:order).permit(order_products: [:quantity])[:order_products].merge(product_id: params[:product_id])
  end

  def setup_order_product
    current_order

    @order_product = current_order.order_products.find_by(product_id: params[:product_id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_genres_helper.rb
module BookGenresHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazon
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = javascript_include_tag 'application'
  %body
    %header
      .navbar.nav-bluebeacon
        .nav-belt
          .nav-left
            .nav-logo
              = link_to("/", class: "nav-logo-link") do
                %span.nav-logo-base.nav-sprite
                %span.nav-logo-ext.nav-sprite
                %span.nav-logo-locale.nav-sprite
              = link_to "プライムを始める", {controller: "products", action: "index"}, class: "nav-logo-tagline nav-sprite nav-prime"
          .nav-right
            .nav-prime
              = image_tag "https://images-na.ssl-images-amazon.com/images/G/09/shazam/swm-800x78-180301-CheckNow-E7Rpa._V500723081_.png",size: "400x39"
          .nav-fill
            .nav-search
              = form_tag("/products/search", method: :get ,class: "link-to-search",name: "keyword") do
                / -binding.pry
                .nav-left
                  .nav-search-scope.nav-sprite
                    .nav-search-facade{"data-value" => "search-alias=aps"}
                    /*  %span.nav-search-label すべて
                    /*  %i.nav-icon
                    /*%span#searchDropdownDescription{:style => "display:none"} Select the department you want to search in
                .nav-right
                  .nav-search-submit.nav-sprite
                    %span#nav-search-submit-text.nav-search-submit-text.nav-sprite 検索
                    %input.nav-input{:tabindex => "7", :type => "submit", :value => ""}/
                .nav-fill
                  .nav-search-field
                    %label#nav-search-label
                    %input.search__query{:name => "keyword", :type => "text", :value => "",style: " height:36px;""width:611px;"}/
        .nav-main
          .nav-left
            .nav-globe-locale-slot
              = link_to("",class: "nav-a nav-a-2") do
                #nav-packard-glow-loc-icon.nav-sprite
                #glow-ingress-block
                  %span.nav-line-1
                    お届け先
                  %span.nav-line-2
                    東京 102-0082&zwnj;
          .nav-right
            .nav-tools
              = link_to("", class: "nav-a nav-a-2") do
                %span.icp-nav-link-inner
                  %span.nav-line-1
                    %span.icp-nav-globe-img-2
                    %span.icp-nav-language
                      JP
                  %span.nav-line-2
                    &nbsp;
                    %span.nav-icon.nav-arrow
                %span.icon-nav-link-border
              -if user_signed_in?
                = link_to( destroy_user_session_path, method: :delete, class: "nav-a nav-a-2") do
                  %span.nav-line-1
                    =current_user.name
                    さん
                    サインアウト
                  %span.nav-line-2
                    アカウント＆リスト
                    %span.nav-icon.nav-arrow
              -else
                = link_to( new_user_session_path, class: "nav-a nav-a-2" ) do
                  %span.nav-line-1
                    こんにちは。 サインイン
                  %span.nav-line-2
                    アカウント＆リスト
                    %span.nav-icon.nav-arrow
              = link_to("", class: "nav-a nav-a-2") do
                %span.nav-line-1
                %span.nav-line-2
                  注文履歴
              = link_to("", class: "nav-a nav-a-2") do
                %span.nav-line-1
                  今すぐ登録
                %span.nav-line-2
                  プライム
                  %span.nav-icon.nav-arrow
              - if user_signed_in?
                = link_to(orders_path, class: "nav-a nav-a-2") do
                  %span.nav-line-1
                  %span.nav-line-2
                    カート
                    %span.nav-icon.nav-arrow
              - else
                = link_to(new_user_session_path, class: "nav-a nav-a-2") do
                  %span.nav-line-1
                  %span.nav-line-2
                    カート
                    %span.nav-icon.nav-arrow
          .nav-fill
            .nav-shop
              = link_to("/parent_categories",class: "nav-a nav-a-2") do
                %span.nav-line-1
                %span.nav-line-2
                  カテゴリー
                  %span.nav-icon.nav-arrow
            .nav-shop-container
              .nav-xshop
                = link_to "マイストア", "", class: "nav-b"
                = link_to "タイムセール", "", class: "nav-b"
                = link_to "ギフト券", "", class: "nav-b"
                = link_to "Amazonで売る", "", class: "nav-b"
                = link_to "ヘルプ", "", class: "nav-b"
                -if user_signed_in?
                  = link_to "お気に入り", user_likes_path(current_user.id),class: "nav-b"
              .nav-supra
                = link_to "Amazonポイント", "", class: "nav-b"
                %span.nav-span :
                = link_to "残高を確認", "", class: "nav-b"

    = yield

    #nav__footer.nav__left-footer
      .nav__footer--back-to-top
        %span.nav__footer--back-to-top-text
          トップへ戻る
      %table.nav__footer--vertical-column
        %tbody
          %tr
            %td.nav__footer--link-col
              .nav__footer--col-head
                Amazonについて
              %ul
                %li.nav-first
                  = link_to '採用情報',"",  class: "nav_a"
                %li
                  = link_to 'Amazonについて', "", class: "nav_a"
                %li
                  = link_to 'プレスリリース', "", class: "nav_a"
                %li
                  = link_to 'Amazonと地球', "", class: "nav_a"
                %li
                  = link_to 'Amazonのコミュニティ活動', "", class: "nav_a"
                %li
                  = link_to 'Amazon Story', "", class: "nav_a"
                %li.nav-last
                  = link_to 'AmazonGlobal', "", class: "nav_a"
            %td.nav__footer--colspace-inner
            %td.nav__footer--link-col
              .nav__footer--col-head
                Amazonでビジネス
              %ul
                %li.nav-first
                  = link_to 'Amazonで売る',"",  class: "nav_a"
                %li
                  = link_to 'フルフィルメント by Amazon', "", class: "nav_a"
                %li
                  = link_to 'Amazon Buisinessで法人販売', "", class: "nav_a"
                %li
                  = link_to 'amazon Pay(決済サービス)', "", class: "nav_a"
                %li
                  = link_to 'アソシエイト(アフィリエイト)', "", class: "nav_a"
                %li
                  = link_to 'Amazonで広告掲載をする', "", class: "nav_a"
                %li
                  = link_to 'Amazonで出版', "", class: "nav_a"
                %li
                  = link_to 'Amazonの仕入れ先になる', "", class: "nav_a"
                %li
                  = link_to 'Amazonの仕入れ先になる', "", class: "nav_a"
                %li.nav-last
                  %span.nav_a_carat
                    ›
                  = link_to '全てのサービスを見る', "", class: "nav_a"
            %td.nav__footer--colspace-inner
            %td.nav__footer--link-col
              .nav__footer--col-head
                Amazonでのお支払い
              %ul
                %li.nav-first
                  = link_to 'Amazonポイント',"",  class: "nav_a"
                %li
                  = link_to 'Amazonギフト券 ', "", class: "nav_a"
                %li
                  = link_to 'Amazon Mastercard', "", class: "nav_a"
                %li
                  = link_to 'クレジットカード&保険', "", class: "nav_a"
                %li
                  = link_to 'パートナーポイントプログラム', "", class: "nav_a"
                %li
                  = link_to 'Amazonギフト券チャージタイプ', "", class: "nav_a"
                %li.nav-last
                  %span.nav_a_carat
                    ›
                  = link_to 'すべての支払方法を見る', "", class: "nav_a"
            %td.nav__footer--colspace-inner
            %td.nav__footer--link-col
              .nav__footer--col-head
                ヘルプ＆ガイド
              %ul
                %li.nav-first
                  = link_to '配送料と配送情報',"",  class: "nav_a"
                %li
                  = link_to 'Amazonプライム', "", class: "nav_a"
                %li
                  = link_to '商品の返品・交換', "", class: "nav_a"
                %li
                  = link_to 'コンテンツと端末の管理', "", class: "nav_a"
                %li
                  = link_to 'ストア・特集一覧', "", class: "nav_a"
                %li
                  = link_to 'Amazonアシスタント', "", class: "nav_a"
                %li.nav-last
                  = link_to 'ヘルプ', "", class: "nav_a"
      .nav__footer--under-line
      .nav__footer--link-line.nav__footer--paditem-line
        %span
          .nav__footer--link-line.nav__footer--logo-line
            = link_to "/" do
              .nav-sprite.nav-logo-base
        %span.icp-container
          .nav__footer--line
            = link_to do
              .icp-nav--globe-img-2.icp-button-globe-2
              %span.icp-color-base
                日本語
              %span.nav-arrow.icp-up-down-arrow
            = link_to do
              %span.icp-flag-3.icp-flag-3-jp
              %span.icp-color-base
                日本
      .nav__footer--link-line.nav__footer--desc-line.nav__footer--line
        %table.nav__footer--moreamazon
          %tbody
            %tr
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  Audible(オーディブル)
                  %br
                  %span.nav__footer--desctext
                    本は朗読で聞こう
                    %br
                    一ヶ月無料体験も
              %td.nav__footer__descsp
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  アマゾンウェブサービス (AWS)
                  %br
                  %span.nav__footer--desctext
                    クラウドコンピューティング
                    %br
                    サービス
              %td.nav__footer__descsp
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  Audible(オーディブル)
                  %br
                  %span.nav__footer--desctext
                    本は朗読で聞こう
                    %br
                    一ヶ月無料体験も
              %td.nav__footer__descsp
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  Audible(オーディブル)
                  %br
                  %span.nav__footer--desctext
                    本は朗読で聞こう
                    %br
                    一ヶ月無料体験も
            %tr
              %td
                &nbsp;
            %tr
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  Audible(オーディブル)
                  %br
                  %span.nav__footer--desctext
                    本は朗読で聞こう
                    %br
                    一ヶ月無料体験も
              %td.nav__footer__descsp
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  アマゾンウェブサービス (AWS)
                  %br
                  %span.nav__footer--desctext
                    クラウドコンピューティング
                    %br
                    サービス
              %td.nav__footer__descsp
              %td.nav__footer__descitem
                = link_to("", class: "nav_a") do
                  Audible(オーディブル)
                  %br
                  %span.nav__footer--desctext
                    本は朗読で聞こう
                    %br
                    一ヶ月無料体験も
              %td.nav__footer__descsp
      .nav__footer--link-line.nav__footer--paditem-line.nav__footer--line.nav__footer--line-diver.nav__footer--copyright
        %ul
          %li.nav_first
            = link_to '利用規約',"",class: "nav_a"
          %li
            = link_to 'プライバシー規約', "", class: "nav_a"
          %li.nav_last
            = link_to 'パーソナライズド広告規約', "", class: "nav_a"
        %span
          © 1996-2018, Amazon.com, Inc. or its affiliates

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazon
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/prodacts/index.html.erb
aaaaaaaaaaaaaaaaaaaaaa

app/views/shared/_book_search.html.haml
#a-page
  %img{:alt => "", :src => "https://images-na.ssl-images-amazon.com/images/G/09/gno/sprites/nav-sprite-global_bluebeacon-V3-1x_optimized._CB516557390_.png", :style => "display:none"}

  #navbar.nav-sprite-v1.nav-bluebeacon.nav-subnav.nav-packard-glow{:role => "navigation"}
    #nav-subnav{"data-category" => "books", "data-digest" => "H1n5rfpwaBm68PM+Agpvlj0NzAM"}
      %a.nav-a.nav-b{:href => "/parent_categories/show", :tabindex => "31"}
        %span.nav-a-content 本
      %a.nav-a{:href => "", :tabindex => "32"}
        %span.nav-a-content 詳細検索
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-2", :href => "", :tabindex => "33"}
        %span.nav-a-content ジャンル一覧
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-3", :href => "", :tabindex => "34"}
        %span.nav-a-content 新刊・予約
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-4", :href => "/gp/bestsellers/books/ref=sv_b_3", :tabindex => "35"}
        %span.nav-a-content Amazonランキング
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-5", :href => "", :tabindex => "36"}
        %span.nav-a-content コミック・ラノベ・BL
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-6", :href => "", :tabindex => "37"}
        %span.nav-a-content 雑誌
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-7", :href => "", :tabindex => "38"}
        %span.nav-a-content 文庫・新書
        %span.nav-arrow
      %a.nav-a{:href => "", :tabindex => "39"}
        %span.nav-a-content Prime Student
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-9", :href => "", :tabindex => "40"}
        %span.nav-a-content バーゲン
        %span.nav-arrow
      %a.nav-a.nav-hasArrow{"data-nav-key" => "lt:subnav-flyout-index-10", :href => "", :tabindex => "41"}
        %span.nav-a-content 古本ストア
        %span.nav-arrow
      %a.nav-a{:href => "", :tabindex => "42"}
        %span.nav-a-content 直接取引で販売促進